name: zzycd
channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  # ------- 1) Conda 主安装部分 -------
  # Python 版本
  - python=3.10.15

  # 以下去除了 Windows 的构建 tag（比如 py310haa95532_0 等），只保留版本
  - anyio=4.6.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=24.2.0
  - babel=2.11.0
  - beautifulsoup4=4.12.3
  - bleach=6.2.0
  - brotli-python=1.0.9
  - ca-certificates=2024.9.24
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - h11=0.14.0
  - httpcore=1.0.2
  - httpx=0.27.0
  - icu=73.1
  - idna=3.7
  - ipykernel=6.29.5
  - ipython=8.27.0
  - ipywidgets=8.1.2
  - jedi=0.19.1
  - jpeg=9e
  - json5=0.9.25
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.2.5
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.10
  - krb5=1.20.1
  - libclang=14.0.6  # 若不需要可移除
  - libffi=3.4.4
  - libpng=1.6.39
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - nbclient=0.8.0
  - nbconvert=7.16.4
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - notebook=7.2.2
  - notebook-shim=0.2.3
  - openssl=3.0.15
  - overrides=7.4.0
  - packaging=24.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pip=24.2
  - platformdirs=3.10.0
  - ply=3.11
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.43
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=2.0.7
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - qtconsole=5.6.0
  - qtpy=2.4.1
  - referencing=0.30.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - send2trash=1.8.2
  - setuptools=75.1.0
  - sip=6.7.12
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - stack_data=0.2.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.14
  - tomli=2.0.1
  - traitlets=5.14.3
  - tzdata=2024b
  - urllib3=2.2.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - widgetsnbextension=4.0.10
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5

  # ------- 2) CUDA 工具包（如果本地驱动支持，可以考虑和 PyTorch 一起装）-------
  - cudatoolkit=11.7

  # ------- 3) 把其余包放到 pip 里，尤其是原先 environment.yml 中 pip: 那些 -------
  - pip:
      # ============== 以下是你原先 pip 下的包，逐一放入 ==============
      - albucore==0.0.23
      - albumentations==2.0.0
      - annotated-types==0.7.0
      - click==8.1.7
      - contourpy==1.3.1
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - efficientnet-pytorch==0.7.1
      - einops==0.8.0
      - eval-type-backport==0.2.0
      - filelock==3.13.1
      - fonttools==4.55.0
      - fsspec==2024.2.0
      - fvcore==0.1.5.post20221221
      - gitdb==4.0.11
      - gitpython==3.1.43
      - huggingface-hub==0.26.2
      - imageio==2.36.1
      - iopath==0.1.10
      - jinja2==3.1.3
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lightning-utilities==0.11.9
      - markupsafe==2.1.5
      - matplotlib==3.9.3
      - mpmath==1.3.0
      - munch==4.0.0
      - networkx==3.2.1
      - ninja==1.11.1.3
      - numpy==1.26.3
      - opencv-python-headless==4.10.0.84
      - pillow==10.2.0
      - portalocker==3.1.1
      - pretrainedmodels==0.7.4
      - protobuf==5.28.3
      - pydantic==2.10.2
      - pydantic-core==2.27.1
      - pyparsing==3.2.0
      - safetensors==0.4.5
      - scikit-image==0.25.0
      - scipy==1.14.1    # 如果不想在 conda 部分固定版本，也可放这里
      - segmentation-models-pytorch==0.3.4
      - sentry-sdk==2.19.0
      - setproctitle==1.3.4
      - simsimd==6.2.0
      - smmap==5.0.1
      - stringzilla==3.10.10
      - sympy==1.13.1
      - tabulate==0.9.0
      - termcolor==2.5.0
      - thop==0.1.1-2209072238
      - tifffile==2024.12.12
      - timm==0.9.7

      # -------------- 关键：PyTorch GPU 版本修改为 +cu117 --------------
      # 前提：PyTorch 是否真的提供了 2.5.1+cu117 的包？
      - torch==2.5.1+cu117
      - torchaudio==2.5.1+cu117
      - torchvision==0.20.1+cu117

      - torchmetrics==1.6.0
      - tqdm==4.67.1
      - typing-extensions==4.12.2
      - wandb==0.18.7
      - yacs==0.1.8
