data_provider:                     # 数据提供器配置
  type: dfc25_track2                  # 数据提供器名称（必须已注册到 DATAPROVIDER）
  root: /opt/data/private/competition/2025 IEEE GRSS Data Fusion Contest Track 2
  base_batch_size: 8            # 基础批量大小
  train_batch_size: 8            # 训练批量大小
  test_batch_size: 64              # 测试批量大小
  num_workers: 8                  # 数据加载线程数
  num_replicas: null               # 分布式训练副本数（可动态设置）
  rank: null                       # 分布式训练 rank（可动态设置）
  shuffle: True                    # 是否打乱数据顺序

  data_aug:                        # 数据增强配置
    train:
      shared:                        # 共享数据增强配置
        - type: flip       # 水平翻转
          params:
            horizontal: True                  # 应用概率
            vertical: True #
        - type: random_scale
          params:
            scale_limit: (-0.5,1.0)
            p: 1.0
        - type: rotate       # 水平翻转
          params:
            limit: (-90,90)                # 应用概率
            p: 1.0 #
        - type: random_crop       # 水平翻转
          params:
            height: 512                 # 应用概率
            width: 512 #
      t1:                   # 针对 t1_image 的专属增强
        - type: gauss_noise          # 高斯噪声
          params:
            std_range: (0.01,0.05)
            mean_range: (0,0)
            p: 0.4    
        - type: color_jitter          # 高斯噪声
          params:
            brightness: (0.8,1.2)
            contrast: (0.8,1.2)
            saturation: (0.8,1.2)
            hue: (-0.1,0.1)
            p: 0.4                   # 应用概率
        - type: coarse_dropout
          params:
            num_holes_range: (1, 2)
            hole_height_range: (0.1, 0.4)
            hole_width_range: (0.1, 0.4)
            p: 0.3
      t2:                   # 针对 t2_image 的专属增强
        - type: gauss_noise          # 高斯噪声
          params:
            std_range: (0.01,0.05)
            mean_range: (0,0)
            p: 0.4   
    val:
      shared:
        - type: noop
      t1:
        - type: noop
      t2:
        - type: noop
    test:
      shared:
        - type: noop
      t1:
        - type: noop
      t2:
        - type: noop
  data_crop:                       # 数据裁剪配置
    train:                         # 训练数据裁剪
      enable: False                # 禁用裁剪       
    val:                           # 验证数据裁剪
      enable: False

run_config:
  n_steps: 300000
  train_only: True
  log_interval: 50
  eval_interval: 5000
  base_lr: 0.00005
  warmup_steps: 5000
  warmup_lr: 1.0e-08
  lr_schedule_name: cosine
  lr_schedule_param: {}
  optimizer_name: adamw
  optimizer_params:
    eps: 1.0e-08
    betas:
    - 0.9
    - 0.999
  weight_decay: 0.0001
  no_wd_keys:
  - norm
  - bias
  grad_clip: 1.0
  mesa: null
  loss:  # 新增的损失函数配置
    type1: dice   # 使用已注册的 "dice" 损失函数
    params1:      # 参数字段
      mode: multiclass
    weight1: 1.0  # 权重
    type2: focal  # 使用已注册的 "focal" 损失函数
    params2:
      alpha: 0.25
      gamma: 2.0
      mode: multiclass
    weight2: 20.0
  exchange: False
  update_freq: 1


net_config:
  name: cbf-hky
ema_decay: 0.9998